export const INITIATE_REQUEST = 'INITIATE_REQUEST';
export const SUCCESS_REQUEST = 'SUCCESS_REQUEST';
export const FAILED_REQUEST = 'FAILED_REQUEST';
export const COMPLETED_REQUEST = 'COMPLETED_REQUEST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_CART_ITEM = 'INCREASE_CART_ITEM';
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM';
